### ISSUE TITLE
Incompatible dependencies

### ISSUE THREAD

**Issue by green3g** [bitovi-components/bitstrap#11]
Not sure if this is being maintained anymore but I figured I would document the issues I encountered while testing the package.

There's a problem with the dependencies currently. 

After fresh `npm install` none of the demos work. I installed the latest `can` and `steal` and then they started working.

System info:
- node: v5.10.0
- npm: v3.5.2
- windows 7 x64

**Comment by matthewp** [comment]
Can you send a PR?

**Comment by green3g** [comment]
https://github.com/bitovi-components/bitstrap/pull/13
